language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      mono: latest
      dotnet: 1.0.0-preview2-003121
    - os: osx
      osx_image: xcode7.2
      mono: latest
      dotnet: 1.0.0-preview2-003121

before_script:
  - chmod +x ./build.sh
script:
  - dotnet --info
  - ./build.sh RunTests.NetCore
